# Form implementation generated from reading ui file 'design.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(539, 428)
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.lbl_rest_message_text = QtWidgets.QLabel(parent=self.centralwidget)
        self.lbl_rest_message_text.setGeometry(QtCore.QRect(180, 120, 201, 71))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.lbl_rest_message_text.setFont(font)
        self.lbl_rest_message_text.setFrameShadow(QtWidgets.QFrame.Shadow.Plain)
        self.lbl_rest_message_text.setObjectName("lbl_rest_message_text")
        self.btn_move_rest_by_5_min = QtWidgets.QPushButton(parent=self.centralwidget)
        self.btn_move_rest_by_5_min.setGeometry(QtCore.QRect(20, 320, 161, 31))
        self.btn_move_rest_by_5_min.setObjectName("btn_move_rest_by_5_min")
        self.btn_move_rest_by_10_min = QtWidgets.QPushButton(parent=self.centralwidget)
        self.btn_move_rest_by_10_min.setGeometry(QtCore.QRect(200, 320, 161, 31))
        self.btn_move_rest_by_10_min.setObjectName("btn_move_rest_by_10_min")
        self.btn_finish_rest = QtWidgets.QPushButton(parent=self.centralwidget)
        self.btn_finish_rest.setGeometry(QtCore.QRect(380, 320, 141, 31))
        self.btn_finish_rest.setObjectName("btn_finish_rest")
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(parent=MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Resty"))
        self.lbl_rest_message_text.setText(_translate("MainWindow", "Time to have a break"))
        self.btn_move_rest_by_5_min.setText(_translate("MainWindow", "Отложить перерыв на 5 мин"))
        self.btn_move_rest_by_10_min.setText(_translate("MainWindow", "Отложить перерыв на 10 мин"))
        self.btn_finish_rest.setText(_translate("MainWindow", "Закончить перерыв"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec())
